### ISSUE TITLE
[DISCUSSION] Prenotazione esami

### ISSUE THREAD

**Issue by hamen** [alter-ego/unisannio-reboot#55]
L'idea e` di integrare _Student Portal_ tra le voci del navigation drawer. I punti che dobbiamo chiarire sono:

- [ ] Il sistema e' unico per tutte le facolta`? 
- [ ] Quali sono le funzionalita` offerte da Student Portal?
- [ ] Quali vogliamo implementare?
- [ ] Qual e` la differenza tra le due url?

**Comment by ShAdOwNeT88** [comment]
ACCESSO AREA STUDENTI
http://www.unisannio.it/servizionline/studenti.html

ACCESSO APPELLI-POST RIFORMA
https://vol.unisannio.it/esse3/auth/studente/Appelli/NoLogin.do

username: 863000247
password: Lacasadiba

**Comment by ShAdOwNeT88** [comment]
per incominciare a rispondere 
1) il sistema anche se presenta siti(interfacce differenti) tutti confluiscono in ACCESSO AREA STUDENTI dove ognuno accede con una matricola e una password

2) funzionalità offerte dallo student portal

**Comment by ShAdOwNeT88** [comment]
/Users/iovineAntonio/Desktop/Schermata 2015-09-01 alle 00.29.07.png

**Comment by ShAdOwNeT88** [comment]
<img width="1440" alt="schermata 2015-09-01 alle 00 29 07" src="https://cloud.githubusercontent.com/assets/1220893/9592360/8c95e7a4-5042-11e5-8627-eb9500bbdeb2.png">

**Comment by hamen** [comment]
Il fatto che il sistema di prenotazione sia unico e` un jackpot. Nelle prossime settimane possiamo iniziare lo studio del portale, degli endpoint, delle chiamate e del parsing.

**Comment by ShAdOwNeT88** [comment]
Ottimo allora possiamo procedere con il prossimo step.
